// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Link struct {
	ID        string
	RefersTo  string
	CreatedBy int64
	Visits    int64
	CreatedAt time.Time
}
