// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links(id, refers_to, created_by)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateLinkParams struct {
	ID        string
	RefersTo  string
	CreatedBy int64
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.ID, arg.RefersTo, arg.CreatedBy)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getLink = `-- name: GetLink :one
SELECT refers_to FROM links
WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var refers_to string
	err := row.Scan(&refers_to)
	return refers_to, err
}

const getLinks = `-- name: GetLinks :many
SELECT id, refers_to, created_by, visits, created_at FROM links
WHERE created_by = $1
`

func (q *Queries) GetLinks(ctx context.Context, createdBy int64) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinks, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.RefersTo,
			&i.CreatedBy,
			&i.Visits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
